### ISSUE TITLE
Google Accounts for WEBD

### ISSUE THREAD

**Issue by huynhj26** [khoiphan21/webdimensions#12]
## Aim
To ensure Web Dimensions is set up on all digital marketing Google Platforms

## Task
- [ ] Set up Google Account
- [ ] Set up Google Adwords
- [ ] Set up Google Analytics
- [ ] Set up Google tag manager
