### ISSUE TITLE
CMS mockups

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/webdimensions#27]
## Tasks
- [x] Create basic mockups for CMS blogging system
    - [x] Basic nav elements
    - [x] New post
        - [x] Design basic elements
            - [x] Buttons - save draft, delete post, publish
            - [x] Preview button
            - [x] Saved indication - tells user whether or not they need to save if changes have been made
    - [x] Published
    - [x] Drafts
    - [x] Queued
    - [x] Trash
