### ISSUE TITLE
Icons for CMS

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/webdimensions#28]
## Tasks
- [ ] New post
- [ ] Calendar icon for queuing posts
- [ ] Clock icon for last edited details
- [ ] Published
- [ ] Drafts
- [ ] Queue
- [ ] Search magnifying glass
- [ ] Settings cog
