### ISSUE TITLE
Mockups for QSF

### ISSUE THREAD

**Issue by andreajaneyee** [khoiphan21/webdimensions#4]
## Tasks
- [x] Mockup for the products page
- [x] Mockup for the about us page
- [x] Mockup for the contact us page
- [x] Mockup for the recipes page
